name: Node Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  node_build:
    name: Build with Node.js
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install Yarn
        run: |
          npm install -g yarn

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: |
          yarn install

      - name: Build Package
        run: |
          ng build angular-baseline

      - name: Build Test App with Yarn
        run: |
          yarn build test-app --configuration production

      - name: Build External Test App with Yarn
        run: |
          yarn build test-app-ext --configuration production
