on:
  push:
    tags:
      - 'v*'

env:
  GITEA_TOKEN: ${{ secrets.TOKEN }}
  GITEA_HOST: ${{ vars.HOST }}
  NPM_EMAIL: ${{ vars.NPM_EMAIL }}

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish NPM Package
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Add NPM-Token
        run: |
          echo "@stereov:registry=https://${GITEA_HOST}/api/packages/baseline/npm/" > ~/.npmrc
          echo "//${GITEA_HOST}/api/packages/baseline/npm/:_authToken=${GITEA_TOKEN}" >> ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc

      - name: Install dependencies
        run: |
          yarn install

      - name: Build Package
        run: |
          ng build angular-baseline

      - name: Build Test App
        run: |
          yarn build test-app --configuration production

      - name: Build External Test App
        run: |
          yarn build test-app-ext --configuration production

      - name: Publish Package
        working-directory: ./projects/angular-baseline
        run: yarn publish
