name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build with Node.js
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Install Yarn and Angular CLI
      run: |
          npm install -g yarn @angular/cli

    - name: Install dependencies
      run: |
          yarn install

    - name: Build Package
      run: |
          ng build baseline

    - name: Build Demo App with Yarn
      run: |
          ng build demo --configuration production

    - name: Testing with Jest
      run: |
          yarn test

    - name: Zip the Package
      run: |
        zip -r package.zip ./projects/baseline

    - name: Copy README.md to package
      run: |
        cp ./README.md ./projects/baseline/README.md

    - name: Release
      working-directory: projects/baseline
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release
